# Generated by Django 4.0.4 on 2022-04-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='liked_songs',
        ),
    ]
