# Generated by Django 4.0.4 on 2022-04-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_remove_film_songs_song_films'),
        ('jwt_auth', '0002_remove_customuser_liked_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_songs',
            field=models.ManyToManyField(default=None, related_name='liked_by', to='songs.song'),
        ),
    ]
