# Generated by Django 4.0.4 on 2022-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_alter_song_films'),
        ('jwt_auth', '0003_customuser_liked_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked_songs',
            field=models.ManyToManyField(null=True, related_name='liked_by', to='songs.song'),
        ),
    ]
