# Generated by Django 4.0.4 on 2022-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_alter_song_films'),
        ('jwt_auth', '0004_alter_customuser_liked_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='songs.song'),
        ),
    ]
