# Generated by Django 4.0.4 on 2022-04-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_remove_song_films'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=300)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.film')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='films',
            field=models.ManyToManyField(through='songs.Context', to='songs.film'),
        ),
        migrations.AddField(
            model_name='context',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song'),
        ),
    ]
