# Generated by Django 4.0.4 on 2022-04-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_rename_director_film_director_rename_year_film_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.CharField(default='image', max_length=200),
            preserve_default=False,
        ),
    ]
