# Generated by Django 4.0.4 on 2022-04-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='songs',
            field=models.ManyToManyField(related_name='films', through='songs.Context', to='songs.song'),
        ),
    ]
