# Generated by Django 4.0.4 on 2022-04-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_alter_film_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='films',
            field=models.ManyToManyField(through='songs.Context', to='songs.film'),
        ),
    ]
