# Generated by Django 4.0.4 on 2022-04-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='song',
        ),
    ]
